version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-fpm
        expose:
            - "9000"
        volumes:
            - ./:/var/www/avavion
            - ./storage/logs/laravel:/var/www/avavion/storage/logs
        container_name: app
        depends_on:
            - db
            - nginx

    nginx:
        image: nginx:1.25.1
        volumes:
            - ./:/var/www/avavion
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        container_name: server
        expose:
            - "80"
            - "443"

    db:
        image: mysql:8.0.33
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        container_name: database
