version: "3.0"

services:
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: php:8.2-fpm
        volumes:
            - ./:/var/www
            - ./storage/logs/laravel:/var/www/storage/logs
        container_name: app
        links:
            - db

    nginx:
        image: nginx:1.25.1
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        container_name: server
        links:
            - php

    db:
        image: mysql:8.0.33
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "avavion"
            MYSQL_ROOT_PASSWORD: "avavionmvm"
        restart: always
        container_name: database
